[server]
port = 8080
name = "RouterWay"
max_cache_size = "100mb"
cache_enabled = true
max_connections = 1000000

[static]
root_directory = "Public"
error_pages_directory = "Public/Errors"

[[api]]
name = "APIV1"
from = "/api/v1"
to = "http://localhost:3000"

[[api]]
name = "APIV2"
from = "/api/v2"
to = "http://localhost:3001"
